// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BlackWhiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));

  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testThemeSwitch() {
    driver.get("https://mail.ru/");

    // Настройка светлой/темной тем
    driver.findElement(By.xpath("//div[2]/div")).click();

    // Светлая тема
    driver.findElement(By.xpath("//label/div")).click();

    Assertions.assertEquals(driver.findElement(By.xpath("/html/body")).getCssValue("background-color"), "rgba(255, 255, 255, 1)");

    // Настройка светлой/темной тем
    driver.findElement(By.xpath("//div[@id='ph-whiteline']/div/div[2]/div")).click();

    // Темная тема
    driver.findElement(By.xpath("//div[@id='ph-whiteline']/div/div[2]/div[2]/div/div/ul/li[2]/label/div")).click();

    Assertions.assertEquals(driver.findElement(By.xpath("/html/body")).getCssValue("background-color"), "rgba(25, 25, 26, 1)");
  }
}
