// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
public class HidePublicationSourceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public static void setup() {
    WebDriverManager.chromedriver().setup();
  }
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));

  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hidePublicationSource() throws InterruptedException {
    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(2576, 1408));
    List<WebElement> tooltips = driver.findElements(By.xpath("//div[@role='presentation']"));
    tooltips.get(0).click();

    new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.presenceOfElementLocated(By.xpath("(//div[@class='pl_ag'])[1]/div/div/button")));
    WebElement card = driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div/div/button"));

    //new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.elementToBeClickable(card));
    card.click();

    /*Actions actions = new Actions(driver);

    WebElement card1 = driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div/div/button"));
    actions.moveToElement(card).moveToElement(card1).click().build().perform();
*/


    //actions.moveToElement(card).click().perform();

    //card.click();

    //driver.findElement(By.cssSelector(".pl_ag:nth-child(1) > .pl_m:nth-child(1) .DocumentCard-dislikeButton-0-1-78 svg")).click();
    driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div/div/div[4]/div/div[2]/button[1]")).click();
    driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div[1]/div"));
    assertThat(driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div[1]/div")).getText(), is("Эта публикация больше не\nпоявится в вашей ленте"));
  }
}
