// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
public class HidePublicationSourceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public static void setup() {
    WebDriverManager.chromedriver().setup();
  }
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));

  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hidePublicationSource() throws InterruptedException {
    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(1376, 1408));
    List<WebElement> tooltips = driver.findElements(By.xpath("//div[@role='presentation']"));
    tooltips.get(0).click();

    new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.presenceOfElementLocated(By.xpath("(//div[@class='pl_ag'])[1]/div/div/button")));
    WebElement card = driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div/div/button"));

    card.click();
    driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div/div/div[4]/div/div[2]/button[2]")).click();
    driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div[1]/div"));
    new WebDriverWait(driver, Duration.ofSeconds(2))
            .until(ExpectedConditions.numberOfElementsToBe(
                    By.xpath("(//div[@class='pl_ag'])[1]/div[1]/div/a"), 0));
    Assertions.assertEquals("Публикации этого источника\nбольше не появятся в вашей ленте",
            driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div[1]/div")).getText());
  }
}
