// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsNot.not;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HidePublicationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public static void setup() {
    String value_name = System.getenv("DRIVER");
    if (value_name.equals("firefox")) {
      WebDriverManager.firefoxdriver().setup();
    } else {
      WebDriverManager.chromedriver().setup();
    }
  }

  @BeforeEach
  public void setUp() {
    String value_name = System.getenv("DRIVER");

    if (value_name.equals("firefox")) {
      driver = new FirefoxDriver();
    } else {
      driver = new ChromeDriver();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hidePublication() {
    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(1376, 1408));
    List<WebElement> tooltips = driver.findElements(By.xpath("//div[@role='presentation']"));
    tooltips.get(0).click();

    new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.presenceOfElementLocated(By.xpath("(//div[@class='pl_ag'])[1]/div/div/button")));
    WebElement card = driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div/div/button"));

    card.click();

    new WebDriverWait(driver, Duration.ofSeconds(2))
            .until(ExpectedConditions.elementToBeClickable(
                    By.xpath("(//div[@class='pl_ag'])[1]/div/div/div[4]/div/div[2]/button[1]")));

    driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div/div/div[4]/div/div[2]/button[1]")).click();
    driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div[1]/div"));
    new WebDriverWait(driver, Duration.ofSeconds(2))
            .until(ExpectedConditions.numberOfElementsToBe(
                    By.xpath("(//div[@class='pl_ag'])[1]/div[1]/div/a"), 0));
    assertThat(driver.findElement(By.xpath("(//div[@class='pl_ag'])[1]/div[1]/div")).getText(), is("Эта публикация больше не\nпоявится в вашей ленте"));
  }
}
