// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
public class LikePublicationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public static void setup() {
    WebDriverManager.chromedriver().setup();
  }

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));

  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void likePublication() {
    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(2576, 1408));
    WebElement likeButton = driver.findElement(By.xpath("(//button[@aria-label='Мне нравится'])[1]"));
    WebElement likeCount = likeButton.findElement(By.xpath("span[2]"));

    int likeNum = Integer.parseInt(likeCount.getText());
    likeButton.click();
    int likeNumAfter = Integer.parseInt(likeCount.getText());

    vars.put("TEXT", js.executeScript("return Number(arguments[0]) + 1", vars.get("TEXT")));
    Assertions.assertEquals(likeNumAfter, likeNum);
  }
}
