// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
public class SubscribeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public static void setup() {
    WebDriverManager.chromedriver().setup();
  }

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void subscribe() {
    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(1710, 1100));
    driver.findElement(By.xpath("//div[@id='ph-whiteline']/div/div[2]/button")).click();
    WebElement iframe = driver.findElement(By.xpath("//iframe[@class='ag-popup__frame__layout__iframe']"));
    driver.switchTo().frame(iframe);
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@name='username']")));

    WebElement usernameInput = driver.findElement(By.xpath("//input[@name='username']"));
    usernameInput.click();
    usernameInput.sendKeys("tpo3test");

    // Кнопенция с предложением ввода пароля
    driver.findElement(By.xpath("//div[@id='root']/div/div/div/div[2]/div/div/form/div[2]/div[2]/div[3]/div/div/div/button/span")).click();

    wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//div[2]/div/div/div/div/div/input")));

    //Форма ввода пароля
    driver.findElement(By.xpath("//div[2]/div/div/div/div/div/input")).sendKeys("mwvNaz7QxQb2uaS");

    // Кнопенция с кнопкой "Войти"
    driver.findElement(By.xpath("//div[@id='root']/div/div/div/div[2]/div/div/form/div[2]/div/div[3]/div/div/div/div/button/span")).click();
    driver.switchTo().defaultContent();

    assertTrue(new WebDriverWait(driver, Duration.ofSeconds(10))
            .until(ExpectedConditions.urlMatches("https://e.mail.ru*")));

    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(1576, 1408));
    js.executeScript("window.scrollTo(0,332.6666564941406)");
    driver.findElement(By.xpath("//main[@id=\'grid\']/div[2]/div[3]/div/div[5]/div/div/div/div/div/button[2]")).click();
    js.executeScript("window.scrollTo(0,142.6666717529297)");
    WebElement subscribeButton = driver.findElement(By.xpath("//div[@class='pl_a']/div[2]/div/div/div/div[2]/button"));
    String expect;
    new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.elementToBeClickable(subscribeButton));
    if (Objects.equals(subscribeButton.getText(), "Подписаться")) {
      expect = "Вы подписаны";
    } else expect = "Подписаться";

    subscribeButton.click();
    new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.elementToBeClickable(subscribeButton));
    // TODO
    assertEquals(expect, subscribeButton.getText());
  }
}
