// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
public class TestSearchFormTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public static void setup() {
    WebDriverManager.chromedriver().setup();
  }

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testSearchForm() {
    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(550, 691));
    driver.switchTo().frame(0);
    driver.findElement(By.xpath("//input[@name=\'text\']")).click();
    driver.findElement(By.xpath("//input[@name=\'text\']")).sendKeys("test");
    driver.switchTo().defaultContent();
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
  }
}
