// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertTrue;
public class TestLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public static void setup() {
    WebDriverManager.chromedriver().setup();
  }

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testLogin() {
    driver.get("https://mail.ru/");
    driver.manage().window().setSize(new Dimension(1710, 1100));
    driver.findElement(By.xpath("//div[@id='ph-whiteline']/div/div[2]/button")).click();
    WebElement iframe = driver.findElement(By.xpath("//iframe[@class='ag-popup__frame__layout__iframe']"));
    driver.switchTo().frame(iframe);
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@name='username']")));

    WebElement usernameInput = driver.findElement(By.xpath("//input[@name='username']"));
    usernameInput.click();
    usernameInput.sendKeys("tpo3test");

    // Кнопенция с предложением ввода пароля
    driver.findElement(By.xpath("//div[@id='root']/div/div/div/div[2]/div/div/form/div[2]/div[2]/div[3]/div/div/div/button/span")).click();

    wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//div[2]/div/div/div/div/div/input")));

    //Форма ввода пароля
    driver.findElement(By.xpath("//div[2]/div/div/div/div/div/input")).sendKeys("mwvNaz7QxQb2uaS");

    // Кнопенция с кнопкой "Войти"
    driver.findElement(By.xpath("//div[@id='root']/div/div/div/div[2]/div/div/form/div[2]/div/div[3]/div/div/div/div/button/span")).click();
    driver.switchTo().defaultContent();

    assertTrue(new WebDriverWait(driver, Duration.ofSeconds(10))
            .until(ExpectedConditions.urlMatches("https://e.mail.ru*")));
  }
}
